### PR TITLE
convert over to param2-based colorization

### PR DESCRIPTION
**Pull request by VanessaE**
Place a default block of wood or fencepost and right-click on it with dye

(only `default:wood`/`default:fence_wood` are supported right now, not acacia/jungle/etc yet)

To make a stair/slab/etc colorized, add `default:wood` to the circular saw, cut, place the stair/slab/etc, then right click it with dye.

Digging either one (block or stair/slab/etc) gives back the default-ish node you originally painted, and the portion of dye you used.

I think this is working fully now.  Dye handling is a problem, but that's unified dyes' territory.

### CODE REVIEW

**Comment by VanessaE** [comment]
wrong drops fixed and commits squashed.

**Comment by VanessaE** [comment]
fixed more stuff and squashed again :-)

**Comment by kilbith** [comment]
HOURS WASTED !

**Comment by VanessaE** [comment]
hah! :-)

**Comment by VanessaE** [comment]
Fixed an LBM conversion bug where already-converted nodes would be re-processed and get the wrong lightness/saturations, and squashed.

**Comment by VanessaE** [comment]
Fixed a missing-moreblocks crash (some stuff didn't check for it first), squashed.

**Comment by VanessaE** [comment]
Local-ized some variabled, squashed,

**Comment by VanessaE** [comment]
The LBM conversion bug fix didn't work right.  fixed, squashed.

**Comment by VanessaE** [comment]
better way to call after_dig_node (always forget I can do it this way)

**Comment by VanessaE** [comment]
Fixed missing after_dig_node for colored stairsplus nodes, squashed.

**Pull request merged**
