### PR TITLE
Add 'stairsplus' as optional dependency

### PR DESCRIPTION
**Pull request by AntumDeluge**
Please correct me if I am wrong, but I believe that 'stairsplus' should be an optional dependency for 'coloredwood'.

### CODE REVIEW

**Comment by VanessaE** [comment]
Stairsplus is part of moreblocks, and is already optional.

**Comment by AntumDeluge** [comment]
Okay, so there is no reason to have it in 'depends.txt'?

**Comment by VanessaE** [comment]
Correct.  Just make sure your copy of Moreblocks is up-to-date (stairsplus has been a part of it for quite a while now, more than a year).

**Comment by AntumDeluge** [comment]
Oh, okay. I'm sorry. Somehow I didn't catch that stairsplus is now part of moreblocks. Thank you.

**Pull request closed without merging**
